let mongoose = require('mongoose');

let liveTestSchema = new mongoose.Schema({
    prize:{
        type:String,
    },
    cost:{
        type:Number,
        requird:true,
        min:0
    },
    description:{
        type:String,
    },
    field:{
        type:[String],
        required:true
    },
    startTime:{
        type:Date,
        required:true
    },
    duration:{
        type:Number,
    },
    endTime:{
        type:Date,
        required:true
    },
    questions:{
        type:[{
            question:{
                type:String,
                required:true
            },
            answer:{
                type:[String],
                required:true
            },
            correct:{
                type:Number,
                required:true,
                min:1,
                max:4
            },
            explanation:{
                type:String,
            },
            marks:{
                type:Number,
                min:1,
                required:true
            }
        }]
    },
    highScore:{
        type:Number,
        required:true
    },
    totalScore:{
        type:Number,
        required:true
    }
});

module.exports = mongoose.Model('liveTestModel',liveTestSchema);